# Generated by Django 4.2.4 on 2023-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(default='profile_imgs/default_user.svg', upload_to='profile_imgs/'),
        ),
    ]
